### ISSUE TITLE
Add EigenLayer Restaking Protocol in Zk-Sync

### ISSUE THREAD

**Issue by imanpajand** [matter-labs/zksync-era#1176]
📝 Description

Please provide the possibility of support for EigenLayer restaking on zk-sync network so that we can somehow interact with L1 and restake Ethereum from L2 side.

🤔 Rationale

Lower fees and adding more demand from the stakers and Injecting powerful money into the ecosystem

 📋 Additional Context

Add zk-sync support in Pendle (Leverage Restaking)

**Comment by feixingxiaozi** [comment]
It appears that you are requesting support for EigenLayer restaking on the zk-sync network, enabling interaction with both Layer 1 (L1) and Layer 2 (L2) of the Ethereum blockchain. The rationale behind this is to take advantage of lower fees and increase demand from stakers, thereby injecting more capital into the ecosystem. Additionally, you mention the desire to add zk-sync support in Pendle, specifically for leverage restaking.

EigenLayer typically refers to a concept in machine learning and neural networks, so I assume it may have a specific meaning in the context of zk-sync and Ethereum that I'm not aware of due to my knowledge cutoff in January 2022.

To achieve support for EigenLayer restaking on zk-sync, you may need to collaborate with developers familiar with zk-sync and the Pendle protocol. Here are some steps you might consider:

Engage with the Community: Reach out to the zk-sync and Pendle communities to discuss the proposal. This could involve participating in relevant forums, Discord channels, or other communication platforms to gather feedback and support.

Collaborate with Developers: Work closely with developers who have expertise in zk-sync and Pendle. They can help assess the technical feasibility, provide insights into potential challenges, and contribute to the implementation.

Proposal and Documentation: Prepare a detailed proposal outlining the technical specifications, benefits, and potential challenges of implementing EigenLayer restaking on zk-sync. Include documentation for developers and users, making the process transparent and accessible.

Contribute to Pendle GitHub: If Pendle has an open-source repository on platforms like GitHub, consider making a contribution by submitting a pull request that integrates zk-sync support for EigenLayer restaking. This involves collaborating with the Pendle development team.

Testing and Iteration: Thoroughly test the proposed changes to ensure they work as intended on both L1 and L2. Address any issues that arise during testing and iterate on the implementation as needed.

Community Feedback and Adoption: Once the feature is implemented, gather feedback from the community and encourage adoption. Address any concerns or issues that users may encounter during real-world usage.

Remember that the success of such a proposal depends on the community's acceptance and the alignment of the changes with the overall goals of the ecosystem. Regular communication and collaboration with relevant stakeholders will be essential throughout the process

**Comment by popzxc** [comment]
Integrations with different projects and protocols are certainly important, but this repository is only dedicated to the implementation of the zkSync Era node.
For general zkSync Era discussions and requests, consider [joining our Discord](https://join.zksync.dev/).
