### ISSUE TITLE
Advocating for Consistent Updates of npm Packages

### ISSUE THREAD

**Issue by Aca1995** [matter-labs/zksync-era#1191]
### **Description**

I've noticed that several npm packages listed in zksync-era repo's package.json file are currently running on older versions. I believe it's crucial to maintain a consistent schedule for updating these packages to their latest versions. Here's why:

👉 **Security Enhancements:** Updated packages often contain security patches and fixes for vulnerabilities discovered in earlier versions. By keeping dependencies up-to-date, we can minimize the risk of potential security threats.

👉 **Bug Fixes and Performance Improvements:** Newer versions typically address bugs and performance issues found in previous releases. Updating packages ensures that we benefit from these improvements, leading to a more stable and efficient codebase.

### Check packages versions

I run the **npm check updates** command and I got this: 

![image](https://github.com/matter-labs/zksync-era/assets/54175342/c7df275b-c704-4e85-b5fa-c64aab6f20ed)

You can see that most of the packages had major updates to their version. I can create PR for simple ones like Prettier, but updating linter will probably result in some additional code errors that would need to be fixed and tested.

**Comment by radical13** [comment]
Solution:

1. Update Dependencies:
   - Firstly, check the documentation for each outdated dependency to understand the changes and upgrade process. Typically, each dependency will have detailed upgrade guides and documentation available.
   - Once you have a clear understanding of the necessary updates, modify the package.json file in the zksync-era repository to specify the latest versions for the outdated dependencies.
   - Run the npm install command to install the updated dependencies.

2. Automated Dependency Management:
   - Consider implementing an automated dependency management tool, such as npm-check-updates or Greenkeeper, which can help you keep track of outdated dependencies and automatically update them to their latest versions.
   - Configure the tool to run periodically and notify you of any available updates. This will ensure that dependencies are regularly checked and updated, reducing the risk of security vulnerabilities and performance issues.

3. Continuous Integration and Testing:
   - Implement a robust continuous integration (CI) system that builds and tests your codebase with the updated dependencies. This will help identify any compatibility issues or regressions caused by the updates.
   - Configure the CI system to automatically run tests and provide feedback on the compatibility of the updated dependencies. This will ensure that the codebase remains stable and functional after each update.

By regularly updating dependencies and maintaining a consistent schedule for these updates, you can ensure improved security, bug fixes, and overall codebase stability in the zksync-era repository.
