### ISSUE TITLE
Is the zksync-era primary network node ready for deployment?

### ISSUE THREAD

**Issue by wo4zhuzi** [matter-labs/zksync-era#15]
Is the zksync-era primary network node ready for deployment? I think the docker-compose.yml and lite versions in this project are almost the same. When can I officially provide a docker library or executable file?

**Comment by shahar4** [comment]
Hello and thanks for reaching out! The main node you see in this repo is exactly what we are running in production. We are working on enabling people to run the node to participate in the network. At this moment you can already run the node locally by following the instruction in `docs/launch.md`. Does this answer your question?

**Comment by sshamanov** [comment]
Hello! Does the node I "can run locally", described in docs/launch.md mean "local node" or "mainnet node that I can run locally"?
I am interested in mainnet RPC node I can run myself.

**Comment by hatemosphere** [comment]
we have a docs to run your own "archival node" here: https://github.com/matter-labs/zksync-era/tree/main/docs/external-node, hovewer:
- it's not GA yet, we are not yet, hence publishing DB backups needed to run it
- since we are not yet de-centralized, all "writes" will still get proxied to our centralized sequencer RPC
please follow our announcements and further developments in this repo to know when EN gets into GA

**Comment by waelsy123** [comment]
Can we still run the the archive node EN from genesis? 
How far are you from publishing DB backups for the archive nodes?
