### ISSUE TITLE
About gpu memory

### ISSUE THREAD

**Issue by wellsqiu** [matter-labs/zksync-era#202]
#### 📝 Description

Is it possible that the gpu memory requirements can be reduced to 8GB or 12/10G?

#### 🤔 Rationale

Most nvidia GPU have 8G or 12/10G of memory. A lot of miners only have those gpus.

**Comment by hatemosphere** [comment]
hey @wellsqiu 
our current plan is to be able to run boojum prover on 16GB VRAM, and we will soon be there.
you can follow changes like https://github.com/matter-labs/era-shivini/pull/7 to keep track on where we are. further optimizations are also possible in the future of course. 

further on please feel free to use discussions in https://github.com/zkSync-Community-Hub/zkync-developers/discussions to raise similar questions  instead of opening issues in this repo. cheers
