### ISSUE TITLE
Error: Failed to create portal config while running zkstack ecosystem init --dev

### ISSUE THREAD

**Issue by yasmuru** [matter-labs/zksync-era#3349]
#### 📝 Description

I'm trying to create a custom zk chain, but after creating the ecosystem and trying to initialise the chain, I'm getting the following error. 

●  Initializing chain xxx
│  
■  Failed to create portal config
│  
▲    0: Invalid name: please ensure the contract and method you're calling exist! failed to decode empty bytes. if you're using jsonrpc this is likely due to jsonrpc returning `0x` in case contract or method don't exist
│  
└  Failed to run command

#### 🔄 Reproduction Steps

I have followed the steps from here https://code.zksync.io/tutorials/custom-zk-chain to create a custom chain. 

#### 🤔 Expected Behavior

The ecosystem should deploy the contracts

#### 😯 Current Behavior

Getting above error

#### 🖥️ Environment

Ubuntu 22.04

#### 📋 Additional Context

Add any other context about the problem here. If applicable, add screenshots to help explain.

#### 📎 Log Output

```
zkstack ecosystem init --dev

┌   ZK Stack CLI 
│
●  Initializing ecosystem
│  
●  Era observability already setup
│  
◇  Installing and building dependencies... done in 27.567574292 secs
│
◇  Deploying ecosystem contracts... done in 12.258236448 secs
│
◇  Accepting governance... done in 0.755145787 secs
│
◇  Accepting governance... done in 0.780022489 secs
│
◇  Accepting governance... done in 0.75739115 secs
│
◇  Accepting governance... done in 1.068025893 secs
│
◇  Accepting governance... done in 0.773003693 secs
│
◇  Accepting governance... done in 0.795428637 secs
│
●  Deploying ERC20 contracts
│  
◇  Deploying ERC20 contracts... done in 0.808529998 secs
│
●  Initializing chain xxxx
│  
■  Failed to create portal config
│  
▲    0: Invalid name: please ensure the contract and method you're calling exist! failed to decode empty bytes. if you're using jsonrpc this is likely due to jsonrpc returning `0x` in case contract or method don't exist
│  
└  Failed to run command
```

**Comment by sanekmelnikov** [comment]
Thank you for reporting an issue!

The error you encountered occurs when specifying a base token address that doesn't exist on L1. This likely happened when you ran `zkstack ecosystem create` and selected "Custom token" as your base token. Since you were running against a clean reth with no ERC20 tokens deployed, ETH was the only valid base token option.

Here's the easiest way to start a chain with a custom base token:
1. First create an ecosystem with ETH as base token:
`zkstack ecosystem create` (make sure to select ETH as the base token)
2. Initialize the ecosystem in dev mode to deploy test tokens:
`zkstack ecosystem init --dev`
3. Create a new chain with custom base token:
`zkstack chain create`
(Select your desired custom base token from the automatically shown deployed addresses, and set this chain as default)
4. Initialize the new chain:
`zkstack chain init`

And definitely agree that the error message could have been more descriptive :)

**Comment by brucewhine** [comment]
I'm also facing similar issue, how to deploy test tokens in the L1 to make it custom token on the L2. Should I include ERC20 contract in the ecosystem configs ? If so, where shall I add it ?

**Comment by yasmuru** [comment]
@sanekmelnikov  Can you help me with this?

**Comment by sanekmelnikov** [comment]
I went through the tutorial and noticed a confusing part. The issue is that it [instructs](https://code.zksync.io/tutorials/custom-zk-chain/customizing-your-chain#configuring-hardhat) you to put the ecosystem governor's private key in `WALLET_PRIVATE_KEY`, but then asks to [confirm](https://code.zksync.io/tutorials/custom-zk-chain/customizing-your-chain#deploying-an-erc20-contract) that the deployer's address (`0x36615Cf349d7F6344891B1e7CA7C72883F5dc049`) is funded.

The correct wallet to fund is the ecosystem governor's wallet.
Its address is `0x8002cD98Cfb563492A6fB3E7C8243b7B9Ad4cc92`
Its private key can be found in `my_elastic_chain/configs/wallets.yaml`
Not to be confused with the chain's governor, which is located inside `my_elastic_chain/chains/...`.

To check the balance after deploying the token, use the following command:
`cast balance --erc20 <0xYOUR_TOKEN_ADDRESS> 0x8002cD98Cfb563492A6fB3E7C8243b7B9Ad4cc92 --rpc-url http://localhost:8545`

Also keep in mind that [Customizing Your ZK Chain](https://code.zksync.io/tutorials/custom-zk-chain) is a continuation of  [Getting Started with ZK Chains](https://code.zksync.io/tutorials/custom-zk-chain), so all steps from the latter must be completed first.

**Comment by yasmuru** [comment]
Works. Thanks @sanekmelnikov
