### ISSUE TITLE
error in running external node

### ISSUE THREAD

**Issue by cliff0412** [matter-labs/zksync-era#50]
i am trying to run a external node. however, it throws error 
```
error: The following required arguments were not provided:
    --database-url <DATABASE_URL>
```

i have specificlly set the env of DATABASE_URL in my command; but it still throws such error
my docker command is
```
docker run matterlabs/external-node-public:v0.0.4 --env-file /root/zksync_nodes/mainnet-config.env --mount type=bind,source=/data/rocksdb/,target=./db/ext-node/ --env DATABASE_URL=postgres://postgres@localhost/zksync_local_ext_node
```

**Comment by tonynguyen-ccl** [comment]
You should have all the config flags in front of the image name.
```
docker run --env-file /root/zksync_nodes/mainnet-config.env --mount type=bind,source=/data/rocksdb/,target=./db/ext-node/ --env DATABASE_URL=postgres://postgres@localhost/zksync_local_ext_node matterlabs/external-node-public:v0.0.4
```

**Comment by qingxueyunfeng** [comment]
Crash happens when I start external node. @tonynguyen-ccl Would you please help to check this issue? Thanks.

thread 'tokio-runtime-worker' panicked at 'Reject requested because of the following error: virtual machine entered unexpected state. Please contact developers and provide transaction details that caused this error. Error description: Assertion error: Tx data offset is incorrect.
 Transaction hash is: 0xe9a1a8601bc9199c80c97169fdc9e1fc7c307185a0c9fa2cfab04098a7840645', core/bin/zksync_core/src/sync_layer/external_io.rs:322:9
stack backtrace:
   0:     0x561d4aeac75a - std::backtrace_rs::backtrace::libunwind::trace::h79937bc171ada62c
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x561d4aeac75a - std::backtrace_rs::backtrace::trace_unsynchronized::h2292bca8571cb919
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x561d4aeac75a - std::sys_common::backtrace::_print_fmt::h9c461f248e4ae90d
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x561d4aeac75a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he9fe6bf1a39182e1
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x561d4aed207e - core::fmt::write::h032658c119c720d7
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/fmt/mod.rs:1208:17
   5:     0x561d4aea6bf5 - std::io::Write::write_fmt::h299fc90dfae41c0d
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/io/mod.rs:1682:15
   6:     0x561d4aeac525 - std::sys_common::backtrace::_print::heb70d25df9937e3f
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x561d4aeac525 - std::sys_common::backtrace::print::had745c0a76b8b521
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x561d4aeae17f - std::panicking::default_hook::{{closure}}::h1ea782cdfa2fd097
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:267:22
   9:     0x561d4aeadebb - std::panicking::default_hook::h1cc3af63455a163c
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:286:9
  10:     0x561d4aeae88c - std::panicking::rust_panic_with_hook::h5cafdc4b3bfd5528
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:688:13
  11:     0x561d4aeae629 - std::panicking::begin_panic_handler::{{closure}}::hf31c60f40775892c
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:579:13
  12:     0x561d4aeacc0c - std::sys_common::backtrace::__rust_end_short_backtrace::h28a5c7be595826cd
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:137:18
  13:     0x561d4aeae332 - rust_begin_unwind
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
  14:     0x561d494db1b3 - core::panicking::panic_fmt::h8fa27a0b37dd98b7
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:64:14
  15:     0x561d49eb09d7 - <zksync_core::sync_layer::external_io::ExternalIO as zksync_core::state_keeper::io::StateKeeperIO>::reject::{{closure}}::h22bbef9aa3281cc5
  16:     0x561d495530c0 - zksync_core::state_keeper::keeper::ZkSyncStateKeeper::process_l1_batch::{{closure}}::h8d6ff528e0ae9295
  17:     0x561d49556fb7 - zksync_core::state_keeper::keeper::ZkSyncStateKeeper::run_inner::{{closure}}::h2cc521af44106701
  18:     0x561d49555552 - zksync_core::state_keeper::keeper::ZkSyncStateKeeper::run::{{closure}}::hbe6563a42d068a0b
  19:     0x561d49620075 - tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::h7217d411eb6e2c76
  20:     0x561d499b6c3d - tokio::runtime::task::core::Core<T,S>::poll::hd881e093e0ecf594
  21:     0x561d496bf787 - tokio::runtime::task::harness::Harness<T,S>::poll::h5b23b07bcbd12157
  22:     0x561d4ae75ee2 - tokio::runtime::scheduler::multi_thread::worker::Context::run_task::h19b6518ddc92f424
  23:     0x561d4ae75173 - tokio::runtime::scheduler::multi_thread::worker::Context::run::hbb60c4d64f743a3a
  24:     0x561d4ae630b9 - tokio::macros::scoped_tls::ScopedKey<T>::set::h71c47b8b6cd8382d
  25:     0x561d4ae74e79 - tokio::runtime::scheduler::multi_thread::worker::run::h2d4d2c64c49912b7
  26:     0x561d4ae7e238 - tokio::runtime::task::core::Core<T,S>::poll::h4b2be6578950b765
  27:     0x561d4ae56daf - tokio::runtime::task::harness::Harness<T,S>::poll::hde3555b7fd1a7309
  28:     0x561d4ae64a38 - tokio::runtime::blocking::pool::Inner::run::h4c35e4a50b52eba6
  29:     0x561d4ae6517a - std::sys_common::backtrace::__rust_begin_short_backtrace::hc2338904a70d789f
  30:     0x561d4ae7753b - core::ops::function::FnOnce::call_once{{vtable.shim}}::h33cea3111e0469fb
  31:     0x561d4aeb1403 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hb77d8d72ebcf79c4
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/alloc/src/boxed.rs:2000:9
  32:     0x561d4aeb1403 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hc08c3353e1568487
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/alloc/src/boxed.rs:2000:9
  33:     0x561d4aeb1403 - std::sys::unix::thread::Thread::new::thread_start::h7168e596cd5e5ce6
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys/unix/thread.rs:108:17
  34:     0x7f62c0ffffa3 - start_thread
  35:     0x7f62c0da706f - clone
  36:                0x0 - <unknown>
2023-08-15T08:08:22.982603Z  INFO zksync_core::state_keeper::batch_executor: State keeper exited with an unfinished batch
2023-08-15T08:08:22.982673Z  INFO zksync_utils::wait_for_tasks: One of the tokio actors unexpectedly finished with error: Reject requested because of the following error: virtual machine entered unexpected state. Please contact developers and provide transaction details that caused this error. Error description: Assertion error: Tx data offset is incorrect.
 Transaction hash is: 0xe9a1a8601bc9199c80c97169fdc9e1fc7c307185a0c9fa2cfab04098a7840645
2023-08-15T08:08:22.982745Z  INFO zksync_core::metadata_calculator::updater: Stop signal received, metadata_calculator is shutting down

**Comment by hatemosphere** [comment]
external node is not yet fully open, please follow announcements and releases in this repo
