### ISSUE TITLE
Can't verify SC bytecode due to missing 1.3.13 compiler in hh plugin and zkSync Mainnet Explorer

### ISSUE THREAD

**Issue by OoXooOx** [matter-labs/zksync-era#60]
When I deploy my SC in mainnet I choose latest version of zksolc compiler in settings. My logs said that it was 1.3.13 version. I successful verify my SC in testnet, but in mainnet I got Error in plugin @matterlabs/hardhat-zksync-verify: Unknown zksolc version: v1.3.13.
I want verify my SC through https://explorer.zksync.io/, but there is no input choice for 1.3.13 compiler.

**Comment by popzxc** [comment]
This should be fixed now. Please feel free to reopen the issue if it persists.

**Comment by macaronchef** [comment]
same issue for v1.3.19
`Error in plugin @matterlabs/hardhat-zksync-verify: Unknown zksolc version: v1.3.19`

**Comment by prateek-zh** [comment]
Same issue for `v1.5.8`
```
ZkSyncBlockExplorer:
Failed to send contract verification request
 Reason: ZkSyncVerifyPluginError: Unknown zksolc version: v1.5.8
```
@popzxc what is the way forward here?

**Comment by popzxc** [comment]
@prateek-zh Hey! This compiler version was released yesterday, and it wasn't added to the contract verifier backend yet. It would be there soon.

**Comment by prateek-zh** [comment]
> @prateek-zh Hey! This compiler version was released yesterday, and it wasn't added to the contract verifier backend yet. It would be there soon.

Thanks for the reply. I figured as much but couldn't find any docs with the compatible versions or how to update them. Could you point me in the right direction so that I can confirm once the version is added?

**Comment by popzxc** [comment]
@prateek-zh compatible versions can be seen on the [explorer page](https://explorer.zksync.io/contracts/verify).
However, we recently [updated](https://github.com/matter-labs/zksync-era/pull/3291) the contract verifier so that it fetches new compiler versions automatically. We found one bug in the implementation, the [PR is open](https://github.com/matter-labs/zksync-era/pull/3378), and hopefully today it will be merged and deployed to the mainnet.

After that this should no longer be an issue.

**Comment by popzxc** [comment]
@prateek-zh latest compiler is now available and you should be able to use it.

**Comment by prateek-zh** [comment]
> @prateek-zh latest compiler is now available and you should be able to use it.

@popzxc thanks!
